exec-once=hyprpm reload
exec-once=systemctl --user start hyprpolkitagent
exec-once=playerctld
exec-once=quickshell
exec-once=udiskie
exec-once=swww-daemon
exec-once=hyprctl setcursor catppuccin-mocha-mauve-cursors 24
exec-once=xsetroot -xcf /usr/share/icons/catppuccin-mocha-mauve-cursors/cursors/left_ptr 24

exec-once=hypridle

exec-once=wl-paste --type text --watch cliphist store
exec-once=wl-paste --type image --watch cliphist store

exec-once=echo "Xft.dpi: 128" | xrdb -merge

exec-once=nm-applet --indicator
exec-once=blueman-applet

# Very hacky way to fix issue with playerctl returning "No player is being controlled by playerctld"
# instead of just removing the mpris player when it is not attached to a player which break
# the player in quickshell (by making sure there is always a player) (I have no idea if there is a
# better way to do this but at least it works)
exec-once=python $HOME/.config/hypr/scripts/dummyPlayer.sh 