# Disable animations
layerrule =  match:namespace noanim, no_anim on
layerrule =  match:namespace bar, animation slide down

# Tiling windows
windowrule = match:class ^(ONLYOFFICE Desktop Editors)$, tile on
windowrule = match:class ^(Minecraft.*)$, tile on
windowrule = match:class ^(steam_app_.*)$, tile on

# Floating windows
windowrule = match:class ^(org.pulseaudio.pavucontrol)$, float on
windowrule = match:class ^(blueman-manager)$, float on
windowrule = match:class ^(nm-connection-editor)$, float on
windowrule = match:class ^(brave-nngceckbapebfimnlniiiahkandclblb-Default)$, float on
windowrule = match:class ^(qt5ct)$, float on
windowrule = match:class ^(qt6ct)$, float on
windowrule = match:class ^(nwg-look)$, float on
windowrule = match:class ^(com.yubico.yubioath)$, float on
windowrule = match:class ^(qalculate-gtk)$, float on
windowrule = match:class ^(Confirm to replace files)$, float on
windowrule = match:class ^(File Operation Progress)$, float on
windowrule = match:class ^(Save File)$, float on
windowrule = match:class ^(Open Folder)$, float on
windowrule = match:class ^(Open File)$, float on
windowrule = match:class ^(seahorse)$, float on
windowrule = match:class ^(Grub-customizer)$, float on
windowrule = match:class ^(file-roller)$, float on
windowrule = match:class ^(system-config-printer)$, float on
windowrule = match:class ^(org.gnome.Firmware)$, float on
windowrule = match:class ^(thunar)$, match:title ^(.*Rename.*)$, float on
windowrule = match:class ^(thunar)$, match:title ^(File Operation Progress)$, float on
windowrule = match:class ^(org.qbittorrent.qBittorrent)$, match:title ^((?!qBittorrent).)$, float on
windowrule = match:class ^(org.prismlauncher.PrismLauncher)$, match:title ^(.*Console window for .*)$, float on

# Windows size
windowrule = match:class ^(org.pulseaudio.pavucontrol)$, size 40% 40%
windowrule = match:class ^(blueman-manager)$, size 40% 40%
windowrule = match:class ^(nm-connection-editor)$, size 40% 40%
windowrule = match:class ^(com.yubico.yubioath)$, size 40% 40%
windowrule = match:class ^(Save File)$, size 40% 40%
windowrule = match:class ^(Open Folder)$, size 40% 40%
windowrule = match:class ^(Open File)$, size 40% 40%
windowrule = match:class ^(system-config-printer)$, size 40% 40%
windowrule = match:class ^(com.hunterwittenborn.Celeste)$, size 40% 40%
windowrule = match:class ^(org.prismlauncher.PrismLauncher)$, match:title title:^(.*Console window for .*)$, size 40% 40%

# Center
windowrule = match:class ^(org.prismlauncher.PrismLauncher)$, center on
windowrule = match:class ^(nwg-processes)$, center on

# Others
windowrule = match:title ^(TestWin)$, pin on