language=en
icon_theme=fluent
font=mpv-osd-symbols

bottomhover=no

time_font_size=20

window_title=no
window_controls=no

ontop_button=no
fullscreen_button=no

osc_color=#000000
title_color=#FFFFFF
seekbarfg_color=#CBA6F7
seekbarbg_color=#555555
volumebar_match_seek_color=yes
time_color=#FFFFFF
chapter_title_color=#FFFFFF
side_buttons_color=#FFFFFF
middle_buttons_color=#FFFFFF
playpause_color=#FFFFFF
held_element_color=#999999
hover_effect_color=#CBA6F7
thumbnail_border_color=#111111
thumbnail_border_outline=#404040

hover_effect=size,color

nibbles_style=single-bar